# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: khovakim <khovakim@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/29 20:13:18 by khovakim          #+#    #+#              #
#    Updated: 2024/12/26 18:12:36 by khovakim         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

###################
###### Colors #####
###################

_GREY=	\033[1;30m
_RED=	\033[1;31m
_GREEN=	\033[1;32m
_YELLOW=\033[1;33m
_BLUE=	\033[1;34m
_PURPLE=\033[1;35m
_CYAN=	\033[1;36m
_WHITE=	\033[1;37m
_NC=	\033[0m

###################
###### Vars #######
###################

NAME = libft.a

CC      = clang
CFLAGS  = -Wall -Wextra -Werorr -g3 -fsanitize=address
INCLUDE = -I ./include/

RM = rm -rf

###################
###### Files ######
###################

SRC_BOOL = \
			ft_isalnum.c     \
			ft_isalpha.c     \
			ft_isdigit.c     \
			ft_isspace.c     \
			ft_isprintable.c \
			ft_is_power_of_2.c
			

SRC_IO = \
			ft_error.c      \
			ft_warning.c    \
			ft_putchar.c    \
			ft_putendl.c    \
			ft_putstr.c     \
			ft_putnbr.c     \
			ft_putchar_fd.c \
			ft_putendl_fd.c \
			ft_putstr_fd.c  \
			ft_putnbr_fd.c

SRC_STR = \
			ft_strlen.c

