# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: khovakim <khovakim@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/29 20:13:18 by khovakim          #+#    #+#              #
#    Updated: 2024/12/26 15:32:48 by khovakim         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC      = clang
CFLAGS  = -Wall -Wextra -Werorr -g3 -fsanitize=address
INCLUDE = -I ./include/

RM = rm -rf

###################
###### Files ######
###################

SRC_BOOL = \
			

SRC_IO = \
			ft_error.c      \
			ft_warning.c    \
			ft_putchar.c    \
			ft_putendl.c    \
			ft_putstr.c     \
			ft_putnbr.c     \
			ft_putchar_fd.c \
			ft_putendl_fd.c \
			ft_putstr_fd.c  \
			ft_putnbr_fd.c

SRC_STR = \
			ft_strlen.c

